services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "7e"
      RAM_SIZE: "2G"
      CPU_CORES: "4"
      DISK_SIZE: "30G"
      REGION: "es-ES"
      KEYBOARD: "es-ES"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
    volumes:
      - /host_shared_folder:/data
    restart: always
    stop_grace_period: 2m
